In [1]:
import torch
x = torch.rand(2,2)
y = torch.rand(2,2)

c:\Users\86433\.conda\envs\yolov6\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x

tensor([[0.7514, 0.3861],
        [0.2436, 0.2535]])

In [3]:
y

tensor([[0.0821, 0.1974],
        [0.2348, 0.9711]])

# 矩阵相加，两种写法

In [4]:
z = x + y # 1
z = torch.add(x,y) # 2
z

tensor([[0.8334, 0.5835],
        [0.4784, 1.2246]])

# 矩阵相减两种方法

In [5]:
z = x - y # 1
z = torch.sub(x,y) # 2
z

tensor([[ 0.6693,  0.1887],
        [ 0.0087, -0.7176]])

# 矩阵相乘两种方法 

In [6]:
z = x * y # 1
z = torch.mul(x,y) # 2
z

tensor([[0.0617, 0.0762],
        [0.0572, 0.2462]])

# 矩阵相除两种方法

In [7]:
z = x / y # 1
z = torch.div(x,y) # 2
z

tensor([[9.1560, 1.9557],
        [1.0371, 0.2611]])

# 矩阵的切片获取

In [10]:
n = torch.rand(5, 3)
print(n)
#遍历所有行，每一行都取第0个元素
print(n[:,0])
#遍历所有行，每一行都取第0个元素
print(n[0,:])
#读第一行，第一列的元素
print(n[1, 1])
#只输出第一行，第一列的元素的值
print(n[1, 1].item())

tensor([[0.5217, 0.8466, 0.6263],
        [0.2707, 0.5524, 0.6572],
        [0.4185, 0.7940, 0.0058],
        [0.3444, 0.6484, 0.9877],
        [0.4874, 0.5078, 0.6890]])
tensor([0.5217, 0.2707, 0.4185, 0.3444, 0.4874])
tensor([0.5217, 0.8466, 0.6263])
tensor(0.5524)
0.552363932132721


# 在gpu运算

In [ ]:
import torch
import numpy as np

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device) #x一步将矩阵放进gpu，y用两步
    y = torch.ones(5)
    y = y.to(device)
    z = x + y   #因为x&y都在gpu上了，所以这样运算会快很多
    #numpy不能在gpu中直接使用，需要转回CPU再用
    z = z.to("cpu")